version: "3.8"

services:

  db:
    image: postgres:12.11-alpine3.16 # needs 12.11 version due to depencency on etl.py
    container_name: db
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=renan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=olist_db
    volumes:
      - ./raw_data/:/raw_data
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"

