version: "3.8"

services:

  db:
    image: postgres:12.11-alpine3.16 # needs 12.11 version due to depencency on etl.py
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=renan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=olist_db
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
      - ./database/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  etl:
    build: ./etl
    container_name: etl
    restart: always
    depends_on:
      - db
    volumes:
      - ./raw_data:/var/lib/postgresql/data

volumes:
  data:
